services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    hostname: plex
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    ports:
      - 32400:32400
    environment:
      - TZ=America/Denver
      #- PLEX_CLAIM=ABC123ABC123ABC
      - ADVERTISE_IP=192.168.1.5:32400,forbes.nwallace.io:32400
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/tv:/tv
      - /media/movies:/movies
      - /docker/plex/config:/config
      - /docker/plex/transcode:/transcode
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    hostname: prowlarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    ports:
      - 9696:9696
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/prowlarr/config:/config
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    hostname: radarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    ports:
      - 7878:7878
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/radarr/config:/config
      - /media:/media
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    hostname: sonarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    ports:
      - 8989:8989
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/sonarr/config:/config
      - /media:/media
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    hostname: bazarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    ports:
      - 6767:6767
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/bazarr/config:/config
      - /media:/media
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard:latest
    restart: unless-stopped
    hostname: wireguard
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    ports:
      - 51820:51820
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
      - SERVERURL=forbes.nwallace.io
      - PEERS=5
      - ALLOWEDIPS=192.168.1.0/16
    volumes:
      - /docker/wireguard/config:/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
  delugevpn:
    container_name: delugevpn
    image: binhex/arch-delugevpn:latest
    restart: unless-stopped
    hostname: delugevpn
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - media
    ports:
      - 8112:8112
    env_file:
      - delugevpn.env
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
      - DEBUG=false
      - LAN_NETWORK=192.168.0.0/16
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_ENABLE_WEBUI_PASSWORD=yes
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=no
      - UMASK=000
      - VPN_PROV=pia
      - VPN_CLIENT=wireguard
      - VPN_ENABLED=true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    privileged: true
    volumes:
      - /docker/delugevpn/config:/config
      - /media:/media
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    hostname: watchtower
    networks:
      - media
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Denver
      - "WATCHTOWER_SCHEDULE=0 0 4 * * *"
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true

networks:
  media:
    name: media
    driver: bridge
    external: false
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.40.0.0/16
